name: lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Run npm install
        run: npm install

      - name: Run lint
        run: npm run lint

