name: Release Node.js Npm Package
on:
  push:
    branches: 
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 14
          check-latest: true
          registry-url: https://npm.pkg.github.com
          always-auth: true
          scope: '@everybyte-io' 
      - name: Install compile dependencies
        run: npm ci --ignore-scripts 
      - name: Compile library
        run: npm run build
      - name: Remove dev dependencies and install prod only 
        run: rm -rf node_modules && npm ci --ignore-scripts --production
      - name: Release
        env: 
          GITHUB_TOKEN: ${{ secrets.ENGAGE_DEVOPS_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release  